<?php

/**
 * General Classes for "marche_en_ligne" theme.
 */

class dm_marche{
//
//  /**
//   * Get array from table.
//   */
//  public static function _getTable($table): array {
//
//    $q=db_select($table,'s');
//
//    $q->fields('s',array('tid', 'parent'));
//    $res=$q->execute();
//
//    $array_key = [];
//    $array_value = [];
//    $array= [];
//
//    while($rec=$res->fetchAssoc()){
//      $tid = $rec['tid'];
//      $parent = $rec['parent'];
//
//      $associative[$tid] = $parent;
//
//      array_push($array_key, $tid);
//      array_push($array_value, $parent);
//    }
//    return $array;
//  }

}


