<?php
/**
 * Implements hook_entity_info_alter().
 *
 *  Adding custom view teaser for commercial node.
 */
function dm_commercial_entity_info_alter(&$entity_info) {
  $entity_info['node']['view modes']['commercial_teaser'] = array(
    'label' => t('Commercial teaser'),
    'custom settings' => TRUE,
  );
}

/**
 * Implements hook_preprocess_node().
 */
function dm_commercial_preprocess_node(&$vars) {
  /**
   * Example template name - node--article--gallery-teaser
   * Use underscores in template suggestions, dashes in the filename.
   */
  if ($vars['view_mode'] == 'commercial_teaser') {
    $vars['theme_hook_suggestions'][] = 'node__' . $vars['type'] . '__commercial_teaser';
  }
}

function dm_commercial_preprocess_views_view_unformatted(&$variables) {

  $view_name = $variables['view']->name;

    if($view_name === 'new_views_front_new_ad') {

      /* Get list node */
      $listNid = (new dm_commercial)->_getNidListNotSort('node', 'commercial_page', 'nid');
      /* Shuffle the array */
      shuffle($listNid);
      /* Set variable */
      $variables['commercial_nid_list'] = $listNid;
    }

}
