<?php
/**
 * Export FILE_USAGE.
 */

/* TABLE NAME */
$name_table_file_usage  = 'file_usage';

/* FIELDS */
$file_usage_fields  = [ 'fid', 'module', 'type', 'id', 'count'];

/**
 * id == nid
 */
/****************************************************************************************************************************************************************/
$file_usage = [
  0 => [
    'fid' => '48942',
    'module' => 'file',
    'type' => 'node',
    'id' => '11004',
    'count' => '1',
  ],
  1 => [
    'fid' => '48935',
    'module' => 'file',
    'type' => 'node',
    'id' => '11003',
    'count' => '1',
  ],
  2 => [
    'fid' => '48938',
    'module' => 'file',
    'type' => 'node',
    'id' => '11003',
    'count' => '1',
  ],
  3 => [
    'fid' => '48924',
    'module' => 'file',
    'type' => 'node',
    'id' => '11002',
    'count' => '1',
  ],
  4 => [
    'fid' => '48925',
    'module' => 'file',
    'type' => 'node',
    'id' => '11002',
    'count' => '1',
  ],
  5 => [
    'fid' => '48926',
    'module' => 'file',
    'type' => 'node',
    'id' => '11002',
    'count' => '1',
  ],
  6 => [
    'fid' => '48927',
    'module' => 'file',
    'type' => 'node',
    'id' => '11002',
    'count' => '1',
  ],
  7 => [
    'fid' => '48928',
    'module' => 'file',
    'type' => 'node',
    'id' => '11002',
    'count' => '1',
  ],
  8 => [
    'fid' => '48929',
    'module' => 'file',
    'type' => 'node',
    'id' => '11002',
    'count' => '1',
  ],
  9 => [
    'fid' => '48930',
    'module' => 'file',
    'type' => 'node',
    'id' => '11002',
    'count' => '1',
  ],
  10 => [
    'fid' => '48931',
    'module' => 'file',
    'type' => 'node',
    'id' => '11002',
    'count' => '1',
  ],
  11 => [
    'fid' => '48932',
    'module' => 'file',
    'type' => 'node',
    'id' => '11002',
    'count' => '1',
  ],
  12 => [
    'fid' => '48915',
    'module' => 'file',
    'type' => 'node',
    'id' => '11001',
    'count' => '1',
  ],
  13 => [
    'fid' => '48911',
    'module' => 'file',
    'type' => 'node',
    'id' => '11001',
    'count' => '1',
  ],
  14 => [
    'fid' => '48912',
    'module' => 'file',
    'type' => 'node',
    'id' => '11001',
    'count' => '1',
  ],
  15 => [
    'fid' => '48913',
    'module' => 'file',
    'type' => 'node',
    'id' => '11001',
    'count' => '1',
  ],
  16 => [
    'fid' => '48914',
    'module' => 'file',
    'type' => 'node',
    'id' => '11001',
    'count' => '1',
  ],
  17 => [
    'fid' => '48906',
    'module' => 'file',
    'type' => 'node',
    'id' => '11000',
    'count' => '1',
  ],
  18 => [
    'fid' => '48907',
    'module' => 'file',
    'type' => 'node',
    'id' => '11000',
    'count' => '1',
  ],
  19 => [
    'fid' => '48909',
    'module' => 'file',
    'type' => 'node',
    'id' => '11000',
    'count' => '1',
  ],
  20 => [
    'fid' => '48910',
    'module' => 'file',
    'type' => 'node',
    'id' => '11000',
    'count' => '1',
  ],
  21 => [
    'fid' => '48901',
    'module' => 'file',
    'type' => 'node',
    'id' => '10999',
    'count' => '1',
  ],
  22 => [
    'fid' => '48895',
    'module' => 'file',
    'type' => 'node',
    'id' => '10999',
    'count' => '1',
  ],
  23 => [
    'fid' => '48896',
    'module' => 'file',
    'type' => 'node',
    'id' => '10999',
    'count' => '1',
  ],
  24 => [
    'fid' => '48897',
    'module' => 'file',
    'type' => 'node',
    'id' => '10999',
    'count' => '1',
  ],
  25 => [
    'fid' => '48898',
    'module' => 'file',
    'type' => 'node',
    'id' => '10999',
    'count' => '1',
  ],
  26 => [
    'fid' => '48899',
    'module' => 'file',
    'type' => 'node',
    'id' => '10999',
    'count' => '1',
  ],
  27 => [
    'fid' => '48900',
    'module' => 'file',
    'type' => 'node',
    'id' => '10999',
    'count' => '1',
  ],
  28 => [
    'fid' => '48902',
    'module' => 'file',
    'type' => 'node',
    'id' => '10999',
    'count' => '1',
  ],
  29 => [
    'fid' => '48903',
    'module' => 'file',
    'type' => 'node',
    'id' => '10999',
    'count' => '1',
  ],
  30 => [
    'fid' => '48904',
    'module' => 'file',
    'type' => 'node',
    'id' => '10999',
    'count' => '1',
  ],
  31 => [
    'fid' => '48894',
    'module' => 'file',
    'type' => 'node',
    'id' => '10998',
    'count' => '1',
  ],
  32 => [
    'fid' => '48889',
    'module' => 'file',
    'type' => 'node',
    'id' => '10998',
    'count' => '1',
  ],
  33 => [
    'fid' => '48891',
    'module' => 'file',
    'type' => 'node',
    'id' => '10998',
    'count' => '1',
  ],
  34 => [
    'fid' => '48893',
    'module' => 'file',
    'type' => 'node',
    'id' => '10998',
    'count' => '1',
  ],
  35 => [
    'fid' => '48873',
    'module' => 'file',
    'type' => 'node',
    'id' => '10997',
    'count' => '1',
  ],
  36 => [
    'fid' => '48874',
    'module' => 'file',
    'type' => 'node',
    'id' => '10997',
    'count' => '1',
  ],
  37 => [
    'fid' => '48875',
    'module' => 'file',
    'type' => 'node',
    'id' => '10997',
    'count' => '1',
  ],
  38 => [
    'fid' => '48876',
    'module' => 'file',
    'type' => 'node',
    'id' => '10997',
    'count' => '1',
  ],
  39 => [
    'fid' => '48877',
    'module' => 'file',
    'type' => 'node',
    'id' => '10997',
    'count' => '1',
  ],
  40 => [
    'fid' => '48878',
    'module' => 'file',
    'type' => 'node',
    'id' => '10997',
    'count' => '1',
  ],
  41 => [
    'fid' => '48879',
    'module' => 'file',
    'type' => 'node',
    'id' => '10997',
    'count' => '1',
  ],
  42 => [
    'fid' => '48880',
    'module' => 'file',
    'type' => 'node',
    'id' => '10997',
    'count' => '1',
  ],
  43 => [
    'fid' => '48881',
    'module' => 'file',
    'type' => 'node',
    'id' => '10997',
    'count' => '1',
  ],
  44 => [
    'fid' => '48882',
    'module' => 'file',
    'type' => 'node',
    'id' => '10997',
    'count' => '1',
  ],
  45 => [
    'fid' => '48883',
    'module' => 'file',
    'type' => 'node',
    'id' => '10997',
    'count' => '1',
  ],
  46 => [
    'fid' => '48884',
    'module' => 'file',
    'type' => 'node',
    'id' => '10996',
    'count' => '1',
  ],
  47 => [
    'fid' => '48885',
    'module' => 'file',
    'type' => 'node',
    'id' => '10996',
    'count' => '1',
  ],
  48 => [
    'fid' => '48886',
    'module' => 'file',
    'type' => 'node',
    'id' => '10996',
    'count' => '1',
  ],
  49 => [
    'fid' => '48887',
    'module' => 'file',
    'type' => 'node',
    'id' => '10996',
    'count' => '1',
  ],
];
